// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA96ZvFhc3WUYKig3rhbGGtxIci_iOm-gA',
//     appId: '1:958710853688:web:a8c5ed27c4086292f476cd',
//     messagingSenderId: '958710853688',
//     projectId: 'belify-461014',
//     authDomain: 'belify-461014.firebaseapp.com',
//     storageBucket: 'belify-461014.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDnwYQFtbpc4mQOUcuE2hZIzxYhTi24D9Y',
//     appId: '1:958710853688:android:08d9ffe1614f53c1f476cd',
//     messagingSenderId: '958710853688',
//     projectId: 'belify-461014',
//     storageBucket: 'belify-461014.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAhJjX_JIpX_zuuPLXbjOfLp2-HAnjkYG0',
//     appId: '1:958710853688:ios:a2bbff854d16198ef476cd',
//     messagingSenderId: '958710853688',
//     projectId: 'belify-461014',
//     storageBucket: 'belify-461014.firebasestorage.app',
//     androidClientId: '958710853688-1nu0fr1mghgnaa8opsa7jqfp1c0mc66l.apps.googleusercontent.com',
//     iosBundleId: 'com.example.belify',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAhJjX_JIpX_zuuPLXbjOfLp2-HAnjkYG0',
//     appId: '1:958710853688:ios:a2bbff854d16198ef476cd',
//     messagingSenderId: '958710853688',
//     projectId: 'belify-461014',
//     storageBucket: 'belify-461014.firebasestorage.app',
//     androidClientId: '958710853688-1nu0fr1mghgnaa8opsa7jqfp1c0mc66l.apps.googleusercontent.com',
//     iosBundleId: 'com.example.belify',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyA96ZvFhc3WUYKig3rhbGGtxIci_iOm-gA',
//     appId: '1:958710853688:web:2582fc08336fa8abf476cd',
//     messagingSenderId: '958710853688',
//     projectId: 'belify-461014',
//     authDomain: 'belify-461014.firebaseapp.com',
//     storageBucket: 'belify-461014.firebasestorage.app',
//   );
// }
